### ISSUE TITLE
The Watering Can loses water in Creative Mode

### ISSUE THREAD

**Issue by C1ffisme** [minetest-mods/crops#2]
The title says it all.

**Comment by sofar** [comment]
minor inconvenience, I'd say. It never breaks.

**Comment by C1ffisme** [comment]
Minor, but worth fixing.

I'd submit a pull request if I wasn't in a hurry right now...

**Comment by sofar** [comment]
I guess you're too scared to do a Pull Request :)

**Comment by C1ffisme** [comment]
Actually, I was leaving for piano lessons, or something like that, and completely forgot.

I guess I can try and do something right now, but I'm probably going to use the github text editor.

**Comment by C1ffisme** [comment]
#3
